### ISSUE TITLE
build system, ms visual studio only?

### ISSUE THREAD

**Issue by alexmyczko** [gpvigano/ArkanoidRemakeSDL#1]
do you plan to provide a makefile cmake or something for macOS or Linux?

**Comment by gpvigano** [comment]
Sorry for my late reply and thank you for your interest.
This is more a programming sample, published "as is", at the moment I have no plans for future developments, also because it was written in C++/SDL and I'm currently working with C#/Unity (even if I hope to find some time to get started with Unreal Engine, mainly for reusing something of what I developed in C++ for many years).
